//
//  Constants.swift
//  Itspay
//
//  Created by Arthur Augusto Sousa Marques on 12/15/16.
//  Copyright © 2016 Compilab. All rights reserved.
//

import UIKit

var COLOR_BUTTON_HEX = "EF3D3C"
var COLOR_NAVIGATION_BAR_HEX = "EF3D3C"

var COLOR_RED_HEX = "EF3D3C"
var COLOR_GREEN_HEX = "65AE42"
var COLOR_LIGHT_GRAY_HEX = "E6E6E6"
var COLOR_BLACK_HEX = "2A2A2A"

var ID_INSTITUICAO = 101
var ID_PROCESSADORA = 10
var ID_USUARIO = 999999

var TIPO_PESSOA = 1

var TIPO_ESTADO_USE_ABROAD = 1
var TIPO_ESTADO_CARD_BLOCK = 2
var TIPO_ESTADO_SAKE = 3
var TIPO_ESTADO_USE_INTERNET = 4
var TIPO_ESTADO_NOTIFICATOINS_ALERT = 5

var ORIGEM_ACESSO = 1
var SISTEMA_OPERACIONAL = 1
var ORIGEM_CADASTRO_LOGIN = 1
var CREDENCIAL = 1

var ID_TARIFAS_TRANSFERENCIA_CARD = 211
var ID_TARIFAS_TRANSFERENCIA_OTHER_BANK = 212
var ID_TARIFAS_CHARGE = 204

var PHONE_SAC = "08009406020"
var PHONE_OUVIDORIA = "(37)35129797"

var EMAIL_SAC = "sac@financialcartoes.com.br"
