//
//  Constants.swift
//  Itspay
//
//  Created by Arthur Augusto Sousa Marques on 12/15/16.
//  Copyright © 2016 Compilab. All rights reserved.
//

import UIKit

//Bahamas
//Build Indentifier = br.com.itspay.bahamascard
var ONE_SIGNAL_APP_ID = "38968233-20ea-4d71-bab7-51e4a8017553"

var COLOR_BUTTON_HEX = "EF3D3C"
var COLOR_NAVIGATION_BAR_HEX = "072E4E"
var COLOR_BUTTON_PRINCIPAL_HEX = "AB772C"
var COLOR_TAG_SELECTED_ITEM = "EF3D3C"
var COLOR_TAG_ITEM = "AB772C"
var TEXT_COLOR_TAG = "FFFFFF"
var TEXT_COLOR_TAG_2 = "FFFFFF"
var LOGO_CLIENT = "BahamasLogo"
var BACKGROUND_CLIENT = "BackBahamas"

var PHONE_SAC = "3232294950"
var PHONE_OUVIDORIA = "3208002859632"
var EMAIL_SAC = "creditoecobranca@bahamascard.com.br"

//Produçao
//var ID_INSTITUICAO = 1201


//    Financial
//   Build Indentifier = br.com.dis.itspay.financial
//var ONE_SIGNAL_APP_ID = "b7eb2b60-b76a-4412-a98d-cacae05f070e"
//
//var COLOR_BUTTON_HEX = "072E4E"
//var COLOR_NAVIGATION_BAR_HEX = "EF3D3C"
//var COLOR_BUTTON_PRINCIPAL_HEX = "EF3D3C"
//var COLOR_TAG_SELECTED_ITEM = "E6E6E6"
//var COLOR_TAG_ITEM = "072E4E"
//var TEXT_COLOR_TAG = "072E4E"
//var TEXT_COLOR_TAG_2 = "FFFFFF"
//var LOGO_CLIENT = "financialLogo"
//var BACKGROUND_CLIENT = "BackFinancial"

//var PHONE_SAC = "08009406020"
//var PHONE_OUVIDORIA = "(37)35129797"
//var EMAIL_SAC = "sac@financialcartoes.com.br"

//Produçao
//var ID_INSTITUICAO = 1401


//Desenv
var ID_INSTITUICAO = 101

var COLOR_BLUE_HEX = "072E4E"
var COLOR_YELLOW_HEX = "AB772C"
var COLOR_RED_HEX = "EF3D3C"
var COLOR_GREEN_HEX = "65AE42"
var COLOR_LIGHT_GRAY_HEX = "E6E6E6"
var COLOR_BLACK_HEX = "2A2A2A"

var ID_INSTITUICAO = 1201
var ID_PROCESSADORA = 10
var ID_USUARIO = 999999

var STATUS = 1
var STATUS_LOST = 1
var STATUS_STEAL = 2

var TIPO_PESSOA = 1

var TIPO_ESTADO_USE_ABROAD = 1
var TIPO_ESTADO_CARD_BLOCK = 2
var TIPO_ESTADO_SAKE = 3
var TIPO_ESTADO_USE_INTERNET = 4
var TIPO_ESTADO_NOTIFICATOINS_ALERT = 5

var ORIGEM_ACESSO = 1
var SISTEMA_OPERACIONAL = 1
var ORIGEM_CADASTRO_LOGIN = 1
var CREDENCIAL = 1

var ID_TARIFAS_TRANSFERENCIA_CARD = 211
var ID_TARIFAS_TRANSFERENCIA_OTHER_BANK = 212
var ID_TARIFAS_CHARGE = 204

