source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.1’
use_frameworks!

target ‘Itspay’ do
    
#pod 'Alamofire'
pod 'pop'    
pod 'ChameleonFramework'    
pod 'CardIO'

end

target ‘ItspayTests' do

end
