source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.1’
use_frameworks!

target ‘Itspay’ do
    
pod 'Alamofire', '~> 4.0'
pod 'pop'    
pod 'ChameleonFramework'    
pod 'CardIO'
pod 'SwiftyJSON'
pod 'ObjectMapper', '~> 2.2'
pod 'PickerFieldsDataHelper'

end

target ‘ItspayTests' do

end
